# -*- coding: utf-8 -*-
"""WhatsCooking_Unay.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RuGdxZBzhsc8io4uVdGy19-m5VGjcsSK
"""

!git clone https://github.com/jackmleitch/whatscooking-deployment.git

import os, shutil
folder = 'whatscooking-deployment'
for f in os.listdir(folder):
    if not f.startswith('.'):
        try:
            shutil.move(os.path.join(folder, f), f)
        except:
            pass
!rm -rf 'whatscooking-deployment'

!pip install unidecode

import nltk
nltk.download('wordnet')

!python rec_sys.py

!python word2vec_rec.py

!python ingredient_parser.py

import pickle, config
with open(config.TFIDF_ENCODING_PATH, "rb") as f:
    tfidf_encodings = pickle.load(f)

with open(config.TFIDF_MODEL_PATH, "rb") as f:
    tfidf = pickle.load(f)